[package]
name = "geonosis-flow"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Authentication flow DSL + graph executor."

[lints]
workspace = true

[dependencies]
geonosis-core = { path = "../geonosis-core" }

async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
chrono.workspace = true
url.workspace = true

[dev-dependencies]
tokio.workspace = true
