{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "geonosis.fullname" . }}
  labels:
    {{- include "geonosis.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "geonosis.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- range .Values.networkPolicy.ingressFromNamespaces }}
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .name | quote }}
      ports:
        - protocol: TCP
          port: 8080
    {{- end }}
  egress:
    # DNS resolution
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    {{- if .Values.networkPolicy.egress.postgres.enabled }}
    - ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.egress.postgres.port }}
    {{- end }}
    {{- if .Values.networkPolicy.egress.redis.enabled }}
    - ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.egress.redis.port }}
    {{- end }}
    {{- if .Values.networkPolicy.egress.otlp.enabled }}
    - ports:
        - protocol: TCP
          port: {{ .Values.networkPolicy.egress.otlp.port }}
    {{- end }}
{{- end }}
