[package]
name = "geonosis-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Geonosis HTTP server binary (axum)."

[lints]
workspace = true

[[bin]]
name = "geonosis-server"
path = "src/main.rs"

[lib]
path = "src/lib.rs"

[dependencies]
geonosis-core = { path = "../geonosis-core" }
geonosis-crypto = { path = "../geonosis-crypto" }
geonosis-storage = { path = "../geonosis-storage", features = ["postgres"] }
geonosis-cache = { path = "../geonosis-cache", features = ["postgres-listen"] }
geonosis-flow = { path = "../geonosis-flow" }
geonosis-protocol-oauth = { path = "../geonosis-protocol-oauth" }
geonosis-protocol-oidc = { path = "../geonosis-protocol-oidc" }
geonosis-protocol-saml-idp = { path = "../geonosis-protocol-saml-idp" }
geonosis-saml-types = { path = "../geonosis-saml-types" }
geonosis-federation-ldap = { path = "../geonosis-federation-ldap", features = ["ldap-runtime"] }
geonosis-broker = { path = "../geonosis-broker", features = ["broker-runtime"] }
geonosis-spi-host = { path = "../geonosis-spi-host", features = ["wasm-runtime"] }
geonosis-authenticators = { path = "../geonosis-authenticators" }
geonosis-audit = { path = "../geonosis-audit", features = ["postgres", "webhook"] }
geonosis-migrate = { path = "../geonosis-migrate" }
geonosis-admin-ui = { path = "../geonosis-admin-ui" }
sqlx.workspace = true

axum.workspace = true
tower.workspace = true
tower-http.workspace = true
hyper.workspace = true
http.workspace = true

tokio.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-opentelemetry.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-otlp.workspace = true
chrono.workspace = true
url.workspace = true
clap.workspace = true
base64.workspace = true
hex.workspace = true
sha2.workspace = true
percent-encoding.workspace = true
blake3.workspace = true
futures.workspace = true
parking_lot.workspace = true

[dev-dependencies]
tokio.workspace = true
ed25519-dalek.workspace = true
pkcs8.workspace = true
rand.workspace = true
