[package]
name = "geonosis-broker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Identity broker (OIDC + SAML SP)."

[lints]
workspace = true

[dependencies]
geonosis-core = { path = "../geonosis-core" }
geonosis-saml-types = { path = "../geonosis-saml-types" }
geonosis-crypto = { path = "../geonosis-crypto" }

async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
chrono.workspace = true
url.workspace = true
